on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build ZMK firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: mono63-zmk
